### PR TITLE
Refactored backend to easy new entries, added background options, added Thouma, added 2.3 and 2.3 weapons and artifacts. Team comp card now available. Plus reworks

### PR DESCRIPTION
**Pull request by Charlotte-91**

### CODE REVIEW

**Comment by altela** [comment]
Hello @Charlotte-91 ,
is this repository accept contribution and pull request?

Edit : 
if that so, could you provide documentation of development (perhaps a readme.md of installation in dev environment)?

thank you!

**Comment by Charlotte-91** [comment]
Hi @Altela ,

Thanks for the interest in my project. 
I'm currently planning to keep this as a solo project, therefore I'm not accepting contributions and pull requests at this time. 

Although I am open to suggestions if you have any. 
Thank you.

**Comment by altela** [comment]
@Charlotte-91 okay then, i'll be keeping this repo under my star list since it's interesting for me :D
thanks for your response, i'd like to point that there's a typo in `team` dropdown as picture below.

Screen Shot 2021-12-20 at 08 38 57

**Comment by Charlotte-91** [comment]
@Altela Thanks so much. It makes me happy to know that people are enjoying my project :)
I'll be sure to fix that spelling issue too! Thanks 👍

**Pull request merged**
